version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd workplace && yarn start"
    ports:
      - "80:3000"
    tty: true